adding shipit to envoy-nginx pipeline

diff --git a/dotfiles/flyw b/dotfiles/flyw
--- a/dotfiles/flyw
+++ b/dotfiles/flyw
@@ -75,3 +75,18 @@ fly-ci () {
   fly -t garden-windows sp -p ci -c $HOME/workspace/garden-windows-ci/pipelines/ci.yml \
   -l <(lpass show --notes Shared-TAS-Runtime/garden-windows-pipeline-secrets )
 }
+
+fly-shipit () {
+  RED='\033[1;31m'
+  NC='\033[0m' # No Color
+
+  lpass status > /dev/null
+  if [[ $? != 0 ]]; then
+    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
+    return
+  fi
+
+  [ "$1" == "-h" ] && echo "Push ci pipeline to concourse" && return
+  fly -t garden-windows sp -p shipit-envoy-nginx -c $HOME/workspace/garden-windows-ci/pipelines/shipit-envoy-nginx.yml \
+  -l <(lpass show --notes Shared-TAS-Runtime/garden-windows-pipeline-secrets )
+}
