Improve ./flyw.sh
Signed-off-by: Anthony Emengo <aemengo@vmware.com>

diff --git a/dotfiles/flyw b/dotfiles/flyw
--- a/dotfiles/flyw
+++ b/dotfiles/flyw
@@ -2,6 +2,15 @@
 
 # Set Pipelines
 fly-envoy-nginx() {
+  RED='\033[1;31m'
+  NC='\033[0m' # No Color
+
+  lpass status > /dev/null
+  if [[ $? != 0 ]]; then
+    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
+    return
+  fi
+
   [ "$1" == "-h" ] && echo "Push envoy-nginx pipeline to concourse" && return
   fly -t garden-windows sp -p envoy-nginx -c $HOME/workspace/garden-windows-ci/pipelines/envoy-nginx.yml \
     -l <(lpass show --notes 'Shared-Greenhouse/env-creds') \
@@ -10,6 +19,15 @@ fly-envoy-nginx() {
 }
 
 fly-misc() {
+  RED='\033[1;31m'
+  NC='\033[0m' # No Color
+
+  lpass status > /dev/null
+  if [[ $? != 0 ]]; then
+    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
+    return
+  fi
+
   [ "$1" == "-h" ] && echo "Push windows-tools pipeline to concourse" && return
   fly -t garden-windows sp -p misc -c $HOME/workspace/garden-windows-ci/pipelines/misc.yml \
     -l <(lpass show --notes 'Shared-Greenhouse/ci-creds') \
@@ -17,6 +35,15 @@ fly-misc() {
 }
 
 fly-winc() {
+  RED='\033[1;31m'
+  NC='\033[0m' # No Color
+
+  lpass status > /dev/null
+  if [[ $? != 0 ]]; then
+    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
+    return
+  fi
+
   [ "$1" == "-h" ] && echo "Push winc pipeline to concourse" && return
   fly -t garden-windows sp -p winc -c $HOME/workspace/garden-windows-ci/pipelines/winc.yml \
     -l <(lpass show --notes 'Shared-Greenhouse/env-creds') \
@@ -25,6 +52,15 @@ fly-winc() {
 }
 
 fly-rootfs() {
+  RED='\033[1;31m'
+  NC='\033[0m' # No Color
+
+  lpass status > /dev/null
+  if [[ $? != 0 ]]; then
+    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
+    return
+  fi
+
   [ "$1" == "-h" ] && echo "Push rootfs pipeline to concourse" && return
   fly -t garden-windows sp -p rootfs -c $HOME/workspace/garden-windows-ci/pipelines/rootfs.yml \
     -l <(lpass show --notes 'Shared-Greenhouse/env-creds') \
@@ -33,6 +69,15 @@ fly-rootfs() {
 }
 
 fly-ci () {
+  RED='\033[1;31m'
+  NC='\033[0m' # No Color
+
+  lpass status > /dev/null
+  if [[ $? != 0 ]]; then
+    echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
+    return
+  fi
+
   [ "$1" == "-h" ] && echo "Push ci pipeline to concourse" && return
   fly -t garden-windows sp -p ci -c $HOME/workspace/garden-windows-ci/pipelines/ci.yml \
   -l <(lpass show --notes 'Shared-Greenhouse/env-creds') \
