Fix bt alias for our bbl'd envs
[#163429722]

Signed-off-by: Natalie Arellano <narellano@pivotal.io>

diff --git a/bin/bash_helpers b/bin/bash_helpers
--- a/bin/bash_helpers
+++ b/bin/bash_helpers
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+declare -r GITHUB_ENVS="aioli,guac,hummus,sriracha,tzatziki"
+
 # Bosh and CF target functions
 bosh_target() {
   local environment=$1
@@ -35,8 +37,7 @@ bosh_target() {
     return
   fi
 
-  local github_envs="aioli,sriracha,hummus,tzatziki"
-  if [[  ",$github_envs," =~ .*\,$environment,.* ]]; then
+  if [[ ",$GITHUB_ENVS," =~ .*\,$environment,.* ]]; then
     _bosh_creds_github $environment
   else
     eval "$(_bosh_creds_gcp $environment true)"
@@ -57,8 +58,7 @@ cf_target() {
     return
   fi
 
-  local github_envs="aioli,sriracha,hummus,tzatziki"
-  if [[  ",$github_envs," =~ .*\,$environment,.* ]]; then
+  if [[ ",$GITHUB_ENVS," =~ .*\,$environment,.* ]]; then
     _bosh_creds_github $environment
     _cf_creds_github $environment
   else
@@ -112,8 +112,32 @@ _env_creds_yml() {
   _cf_creds_yml $1
 }
 
+_get_jumpbox_creds() {
+  bbl_state_dir=$1
+  local uppercase_environment=$(echo $2 | awk '{print toupper($0)}')
+
+  local jumpbox_ip="$(bbl --state-dir=$bbl_state_dir jumpbox-address 2>&1)"
+  if [[ $? -ne 0 ]]; then
+    echo "echo \"Failed to get jumpbox address: $jumpbox_ip\""
+    return
+  fi
+
+  local jumpbox_ssh_key="$(bbl --state-dir=$bbl_state_dir ssh-key)"
+  if [[ $? -ne 0 ]]; then
+    echo "echo \"Failed to get jumpbox ssh key: $jumpbox_ssh_key\""
+    return
+  fi
+
+  echo "${uppercase_environment}_JUMPBOX_URL: $jumpbox_ip:22"
+  echo "${uppercase_environment}_JUMPBOX_IP: $jumpbox_ip"
+
+  local formatted_key=$(echo "$jumpbox_ssh_key" | sed 's/^/  /')
+  echo -e "${uppercase_environment}_JUMPBOX_SSH_KEY: |\n$formatted_key"
+}
+
 _bosh_creds_yml() {
   local environment=$1
+  local uppercase_environment=$(echo $environment | awk '{print toupper($0)}')
 
   project_name=$(_project_name $environment)
   if [[ -z "$project_name" ]]; then
@@ -121,13 +145,23 @@ _bosh_creds_yml() {
     return
   fi
 
-  local uppercase_environment=$(echo "$environment" | awk '{print toupper($0)}')
-
-  local github_envs="aioli,sriracha,hummus,tzatziki"
-  if [[  ",$github_envs," =~ .*\,$environment,.* ]]; then
-    _bosh_creds_github $environment
+  if [[ ",$GITHUB_ENVS," =~ .*\,$environment,.* ]]; then
+    _bosh_creds_github $environment true
+    if [ $? -ne 0 ]; then
+      echo "_bosh_creds_github failed"
+      return
+    fi
   else
+    # TODO: remove this when every environment uses the github repo for its creds
     eval "$(_bosh_creds_gcp $environment true)"
+
+    if gsutil ls gs://$project_name/bbl-state.json > /dev/null 2>&1; then
+      local bbl_state_dir=$(mktemp -d)
+      gsutil cp gs://$project_name/bbl-state.json $bbl_state_dir >/dev/null 2>&1
+      gsutil cp -r gs://$project_name/vars $bbl_state_dir >/dev/null 2>&1
+      _get_jumpbox_creds $bbl_state_dir $environment
+      rm -rf $bbl_state_dir
+    fi
   fi
 
   echo "${uppercase_environment}_BOSH_CLIENT: $BOSH_CLIENT"
@@ -136,40 +170,13 @@ _bosh_creds_yml() {
 
   local formatted_cert=$(echo "$BOSH_CA_CERT" | sed 's/^/  /')
   echo -e "${uppercase_environment}_BOSH_CA_CERT: |\n$formatted_cert"
-
-  if gsutil ls gs://$project_name/bbl-state.json > /dev/null 2>&1; then
-    local bbl_state_dir=$(mktemp -d)
-    gsutil cp gs://$project_name/bbl-state.json $bbl_state_dir >/dev/null 2>&1
-    gsutil cp -r gs://$project_name/vars $bbl_state_dir >/dev/null 2>&1
-
-    local jumpbox_ip="$(bbl --state-dir=$bbl_state_dir jumpbox-address 2>&1)"
-    if [[ $? -ne 0 ]]; then
-      echo "echo \"Failed to get jumpbox address: $jumpbox_ip\""
-      return
-    fi
-
-    local jumpbox_ssh_key="$(bbl --state-dir=$bbl_state_dir ssh-key)"
-    if [[ $? -ne 0 ]]; then
-      echo "echo \"Failed to get jumpbox ssh key: $jumpbox_ssh_key\""
-      return
-    fi
-
-    rm -r $bbl_state_dir
-
-    echo "${uppercase_environment}_JUMPBOX_URL: $jumpbox_ip:22"
-    echo "${uppercase_environment}_JUMPBOX_IP: $jumpbox_ip"
-
-    local formatted_key=$(echo "$jumpbox_ssh_key" | sed 's/^/  /')
-    echo -e "${uppercase_environment}_JUMPBOX_SSH_KEY: |\n$formatted_key"
-  fi
 }
 
 _cf_creds_yml() {
   local environment=$1
   local uppercase_environment=$(echo "$environment" | awk '{print toupper($0)}')
 
-  local github_envs="aioli,sriracha,hummus,tzatziki"
-  if [[  ",$github_envs," =~ .*\,$environment,.* ]]; then
+  if [[ ",$GITHUB_ENVS," =~ .*\,$environment,.* ]]; then
     _cf_creds_github $environment
   else
     eval "$(_cf_creds $environment)"
@@ -181,6 +188,7 @@ _cf_creds_yml() {
 
 _bosh_creds_github() {
   local environment=$1
+  local print_jumpbox_creds=$2
 
   local envs="/tmp/garden-windows-environments"
 
@@ -189,12 +197,19 @@ _bosh_creds_github() {
     rm -rf "${envs}"
   fi
 
-  mkdir -p "${envs}"
-  git clone git@github.com:pivotal/garden-windows-environments.git ${envs}
+  mkdir -p "${envs}" &> /dev/null
+  git clone git@github.com:pivotal/garden-windows-environments.git ${envs} &> /dev/null
+  if [ $? -ne 0 ]; then
+    echo "'git clone git@github.com:pivotal/garden-windows-environments.git' failed; make sure to run 'load-key'"
+    return 1
+  fi
 
-  pushd "${envs}/${environment}"
+  pushd "${envs}/${environment}" &> /dev/null
     eval "$(bbl print-env)"
-  popd
+    if test $print_jumpbox_creds; then
+      _get_jumpbox_creds "${envs}/${environment}" $environment
+    fi
+  popd &> /dev/null
 
   rm -rf "${envs}"
 
@@ -282,15 +297,15 @@ _cf_creds_github() {
   local environment=$1
 
   local envs="/tmp/garden-windows-environments"
-  mkdir -p "${envs}"
+  mkdir -p "${envs}" &> /dev/null
 
-  git clone git@github.com:pivotal/garden-windows-environments.git ${envs}
+  git clone git@github.com:pivotal/garden-windows-environments.git ${envs} &> /dev/null
 
-  pushd "${envs}/${environment}"
+  pushd "${envs}/${environment}" &> /dev/null
     export CREDHUB_SECRET=$(bosh int --path /credhub_admin_client_secret cf/creds.yml)
 
     export ADMIN_PASSWORD=$(bosh int --path /cf_admin_password cf/vars.yml)
-  popd
+  popd &> /dev/null
 
   rm -rf "${envs}"
 
