Revive deploy_concourse_workers script
Signed-off-by: Victoria Henry <vhenry@pivotal.io>
Signed-off-by: Anthony Emengo <aemengo@pivotal.io>

diff --git a/bin/deploy_concourse_windows_workers b/bin/deploy_concourse_windows_workers
--- a/bin/deploy_concourse_windows_workers
+++ b/bin/deploy_concourse_windows_workers
@@ -1,11 +1,15 @@
 #!/usr/bin/env bash
 
-set -e
+RED='\033[1;31m'
+NC='\033[0m' # No Color
 
-if [[ -z "$(gcloud config list --format='value(core.account)')" ]]; then
-  echo 'Must log in using `gcloud auth login`'
+lpass status > /dev/null
+if [[ $? != 0 ]]; then
+  echo -e "${RED}Error${NC}: You must log into lastpass before running this script."
   exit 1
 fi
+
+set -e
 
 CONCOURSE_DEPLOYMENT=${CONCOURSE_DEPLOYMENT:-$HOME/workspace/concourse-bosh-deployment}
 if [[ ! -d $CONCOURSE_DEPLOYMENT ]]; then
@@ -23,9 +27,6 @@ fi
 
 source $GARDEN_WINDOWS_CI/bin/bash_helpers
 
-concourse_vars_project="cf-greenhouse-spitfire"
-DIR=$(mktemp -d)
-
 bosh_target "spitfire"
 
 bosh -d concourse-worker-1803 deploy ${CONCOURSE_DEPLOYMENT}/cluster/external-worker.yml \
@@ -39,10 +40,15 @@ bosh -d concourse-worker-1803 deploy ${CONCOURSE_DEPLOYMENT}/cluster/external-wo
   -o ${GARDEN_WINDOWS_CI}/operations/concourse/windows-tools-1803.yml \
   -o ${GARDEN_WINDOWS_CI}/operations/concourse/use-1803-windows2016-stemcell.yml \
   -o ${GARDEN_WINDOWS_CI}/operations/concourse/windows-bosh-ssh.yml \
-  -v windows_worker_tag=1803 \
   -l ${CONCOURSE_DEPLOYMENT}/versions.yml \
-  -l <(gsutil cat gs://$concourse_vars_project/concourse/vars.yml) \
-  -l <(gsutil cat gs://$concourse_vars_project/concourse/creds.yml) \
+  -l <(lpass show --notes Shared-Greenhouse/ci-creds) \
+  -v team=windows-containers \
+  -v tsa_host=hush-house.pivotal.io \
+  -v tsa_port=2222 \
+  -v network_name=private \
+  -v windows_worker_vm_type=n1-highmem-16 \
+  -v windows_worker_ephemeral_disk=500GB_ephemeral_disk \
+  -v windows_worker_tag=1803 \
   --no-redact
 
 bosh -d concourse-worker-2019 deploy ${CONCOURSE_DEPLOYMENT}/cluster/external-worker.yml \
@@ -56,8 +62,13 @@ bosh -d concourse-worker-2019 deploy ${CONCOURSE_DEPLOYMENT}/cluster/external-wo
   -o ${GARDEN_WINDOWS_CI}/operations/concourse/windows-tools-2019.yml \
   -o ${GARDEN_WINDOWS_CI}/operations/concourse/use-windows2019-stemcell.yml \
   -o ${GARDEN_WINDOWS_CI}/operations/concourse/windows-bosh-ssh.yml \
-  -v windows_worker_tag=2019 \
   -l ${CONCOURSE_DEPLOYMENT}/versions.yml \
-  -l <(gsutil cat gs://$concourse_vars_project/concourse/vars.yml) \
-  -l <(gsutil cat gs://$concourse_vars_project/concourse/creds.yml) \
+  -l <(lpass show --notes Shared-Greenhouse/ci-creds) \
+  -v team=windows-containers \
+  -v tsa_host=hush-house.pivotal.io \
+  -v tsa_port=2222 \
+  -v network_name=private \
+  -v windows_worker_vm_type=n1-highmem-16 \
+  -v windows_worker_ephemeral_disk=500GB_ephemeral_disk \
+  -v windows_worker_tag=2019 \
   --no-redact
