Update deploycf to work with 1709 and 1803
- Fixes the out of sync problem
- Added another arg `deploy_cf hummus 1803`

[#161735148]

Signed-off-by: Yael Harel <yharel@pivotal.io>
Signed-off-by: Amin Jamali <ajamali@pivotal.io>

diff --git a/bin/deploy_cf b/bin/deploy_cf
--- a/bin/deploy_cf
+++ b/bin/deploy_cf
@@ -38,45 +38,50 @@ BOSH_DEPLOYMENT=${BOSH_DEPLOYMENT:-$HOME/workspace/bosh-deployment}
 
 bosh -d cf update-runtime-config ${BOSH_DEPLOYMENT}/runtime-configs/dns.yml --name dns
 
-if [ "$2" = "--use-credhub" ]
-then
-  echo "Deploying cf on $environment with credhub"
-  bosh -d cf deploy ${CF_DEPLOYMENT}/cf-deployment.yml \
+command="bosh -d cf deploy ${CF_DEPLOYMENT}/cf-deployment.yml \
     -o ${CF_DEPLOYMENT}/operations/use-latest-stemcell.yml \
-    -o ${CF_DEPLOYMENT}/operations/windows-cell.yml \
-    -o ${CF_DEPLOYMENT}/operations/use-latest-windows-stemcell.yml \
-    -o ${CF_DEPLOYMENT}/operations/windows2016-cell.yml \
-    -o ${CF_DEPLOYMENT}/operations/use-latest-windows2016-stemcell.yml \
+    -o ${CF_DEPLOYMENT}/operations/windows2012R2-cell.yml \
+    -o ${CF_DEPLOYMENT}/operations/use-latest-windows2012R2-stemcell.yml \
     -o ${CF_DEPLOYMENT}/operations/scale-to-one-az.yml \
     -o ${CF_DEPLOYMENT}/operations/stop-skipping-tls-validation.yml \
     -o ${GARDEN_WINDOWS_CI}/operations/latest-garden-runc.yml \
     -o ${GARDEN_WINDOWS_CI}/operations/latest-winc.yml \
     -o ${GARDEN_WINDOWS_CI}/operations/enable-rdp.yml \
+    -v system_domain=$environment.cf-app.com \
+    --skip-drain \
+  "
+
+
+if [ "$2" = "1709" ]; then
+  command="$command -o ${CF_DEPLOYMENT}/operations/windows2016-cell.yml \
     -o ${GARDEN_WINDOWS_CI}/operations/enable-rdp-2016.yml \
     -o ${GARDEN_WINDOWS_CI}/operations/windows2016-debug.yml \
-    -v system_domain=$environment.cf-app.com \
-    --skip-drain
+    -o ${CF_DEPLOYMENT}/operations/use-latest-windows2016-stemcell.yml \
+    "
+elif [ "$2" = "1803" ]; then
+  command="$command -o ${CF_DEPLOYMENT}/operations/windows1803-cell.yml \
+    -o ${GARDEN_WINDOWS_CI}/operations/enable-rdp-1803.yml \
+    -o ${GARDEN_WINDOWS_CI}/operations/windows1803-debug.yml \
+    -o ${CF_DEPLOYMENT}/operations/use-latest-windows1803-stemcell.yml \
+    "
+else
+  echo "Invalid version, please select 1709 or 1803"
+  exit 1
+fi
+
+if [ "$3" = "--use-credhub" ]
+then
+  echo "Deploying cf on $environment with credhub"
+  eval $command
 else
   echo "Deploying cf on $environment without credhub. To use credhub use option --use-credhub"
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
   gsutil cp gs://$project_name/cf/creds.yml $DIR/creds.yml
-  bosh -d cf deploy ${CF_DEPLOYMENT}/cf-deployment.yml \
-    -o ${CF_DEPLOYMENT}/operations/use-latest-stemcell.yml \
-    -o ${CF_DEPLOYMENT}/operations/windows-cell.yml \
-    -o ${CF_DEPLOYMENT}/operations/use-latest-windows-stemcell.yml \
-    -o ${CF_DEPLOYMENT}/operations/windows2016-cell.yml \
-    -o ${CF_DEPLOYMENT}/operations/use-latest-windows2016-stemcell.yml \
-    -o ${CF_DEPLOYMENT}/operations/scale-to-one-az.yml \
-    -o ${CF_DEPLOYMENT}/operations/stop-skipping-tls-validation.yml \
-    -o ${GARDEN_WINDOWS_CI}/operations/latest-garden-runc.yml \
-    -o ${GARDEN_WINDOWS_CI}/operations/latest-winc.yml \
-    -o ${GARDEN_WINDOWS_CI}/operations/enable-rdp.yml \
-    -o ${GARDEN_WINDOWS_CI}/operations/enable-rdp-2016.yml \
-    -o ${GARDEN_WINDOWS_CI}/operations/windows2016-debug.yml \
-    -l <(gsutil cat gs://$project_name/cf/vars.yml) \
+  command="$command -l <(gsutil cat gs://$project_name/cf/vars.yml) \
     --vars-store $DIR/creds.yml \
     -v system_domain=$environment.cf-app.com \
-    --skip-drain
+    "
+  eval $command
   gsutil cp $DIR/creds.yml gs://$project_name/cf/creds.yml
   rm $DIR/creds.yml
 fi
