Updating blobs for offline rootfs will fail on windows2016fs.
- We do not upload this blob to an s3 bucket so this command will always
fail. We only want to upload the golang blob. There is no way to specify
_which_ blobs you want to upload so we have to run it for all of them
and ignore the failure.

[#169768022]

Signed-off-by: Genevieve LEsperance <glesperance@pivotal.io>

diff --git a/tasks/bosh-update-blob/run b/tasks/bosh-update-blob/run
--- a/tasks/bosh-update-blob/run
+++ b/tasks/bosh-update-blob/run
@@ -18,12 +18,14 @@ pushd release-repo
   oldBlob=$(bosh blobs | grep golang | awk '{print $1}')
   bosh remove-blob $oldBlob
 
-  # Ensure we don't upload other blobs.
-  rm -rf blobs/*
-
   bosh add-blob $zipPath "golang/$zipName"
 
+  # When bosh upload-blobs runs, it will upload the golang blob
+  # to the bucket but then fail trying to upload the windows2016fs blob.
+  # This is okay because we do not want to publish this blob to a bucket.
+  set +e
   bosh upload-blobs
+  set -e
 
   if [ -n "$(git status --porcelain)" ]; then
     git config user.email "pivotal-netgarden-eng@pivotal.io"
